apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ./configmap.yaml
 - ./deployment.yaml
 - ./service.yaml
 - ./ingress.yaml
 - ./persistentvolume.yaml
 - ./persistentvolumeclaim.yaml
images:
  - name: MAIN-ONE-IMAGE
  - name: MAIN-TWO-IMAGE
