name: Delete environment on branch remove

on: [delete]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: dwk-cluster-2
  GKE_ZONE: europe-central2-a

jobs:
  remove:
    name: Remove environment on branch delete
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP connection
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GKE_PROJECT_ID }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
      
      - name: Authenticate
        run: gcloud --quiet auth configure-docker

      - name: Get credentials
        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
  
      - name: Setup Kustomize
        run: |
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize
      
      - name: Deploy on GKE
        run: |
          cd deploy
          kubectl config set-context --current --namespace=${GITHUB_REF#refs/heads/}
          kubectl delete -k .
          kubectl delete namespace ${GITHUB_REF#refs/heads/} || true
          kubectl rollout status deployment/$DEPLOYMENT_NAME  